version: '2.0'

services:
  traefik:
    container_name: traefik_container
    image: traefik
    restart: always
    networks:
      - traefik
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme/acme.json:/acme.json

networks:
   traefik:
     external:
       name: traefik
